In [100]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [101]:
df = pd.read_csv('bank-additional-full.csv', sep=";")
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [102]:
y = df.iloc[0:, 20] #this is the output variable dataframe
X = df.iloc[0:, 0:20] #this is the rest of the factors except the output variable

In [103]:
'''STEP 2'''
from sklearn.model_selection import train_test_split

#we use train_test_split to randomly generate sets and we also split the output value already
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=(2021-10-25)) # 20% test, 80% train

In [104]:
'''STEP 3'''
#drop the 'duration' column from both train and test since it will affect the output highly
X_train = X_train.drop(columns=['duration'])
X_test = X_test.drop(columns=['duration'])

#X_train

In [105]:
'''STEP 4 -> turn categorical variables between 1-10 into dummy variables'''
#categorical vars in a list 
listOfCats = ['job','marital','education','default','housing','loan','contact','month','day_of_week']
X_train = pd.get_dummies(data=X_train, columns=['job','marital','education','default','housing','loan','contact','month','day_of_week'])
X_test = pd.get_dummies(data=X_test, columns=['job','marital','education','default','housing','loan','contact','month','day_of_week'])

X_train

,age,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed
10155,49,2,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,...,0,0,0,0,0,0,0,1,0,0
11854,38,5,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,...,0,0,0,0,0,1,0,0,0,0
23243,59,10,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,...,0,0,0,0,0,0,0,0,1,0
20384,38,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,...,0,0,0,0,0,0,0,0,1,0
28110,47,2,999,0,nonexistent,-1.8,93.075,-47.1,1.479,5099.1,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17987,31,13,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,...,0,0,0,0,0,0,0,0,1,0
20299,29,5,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,...,0,0,0,0,0,0,1,0,0,0
14556,49,1,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,...,0,0,0,0,0,0,0,0,1,0
28981,47,1,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,...,0,0,0,0,0,1,0,0,0,0
32764,35,5,999,0,nonexistent,-1.8,92.893,-46.2,1.299,5099.1,...,0,1,0,0,0,0,1,0,0,0

In [106]:
'''STEP 5: running the data on a categorical naive bayes classifier'''
from sklearn.naive_bayes import CategoricalNB

cnb = CategoricalNB()
cnb.fit(X_train, y_train)

ValueError: invalid literal for int() with base 10: 'nonexistent'